# SPDX-License-Identifier: Apache-2.0

CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_CPP_EXCEPTIONS=n
CONFIG_TENSORFLOW_LITE_MICRO=y
CONFIG_ETHOS_U=y
CONFIG_ETHOS_U85_256=y
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_HEAP_MEM_POOL_SIZE=16384
CONFIG_REQUIRES_FLOAT_PRINTF=y
CONFIG_LOG=y
CONFIG_LOG_PRINTK=n

# The /ns board builds TF-M to configure TrustZone and enter Zephyr.
CONFIG_TFM_BL1=y
CONFIG_TFM_BL2=y
